baseURL = "https://phantomklange.com/"
languageCode = "en-us"
title = "Phantomklänge"
theme = "hugo-brewm"  # Match your theme's folder name

# Taxonomy settings
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors" # Writers, Directors
  period = "periods"  # For historical periods (fin de siècle, etc.)
  
[params]
  description = "Explorations in literature, film, and philosophy"
  math = true  # Enable math rendering globally

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30